### ISSUE TITLE
Cart / Shipping calculation

### ISSUE THREAD

**Issue by admench** [pixelpeter/laravel5-woocommerce-api-client#33]
Hey, Thanks for creating this great repo!

Not an issue, but just a question, I am planning on creating a laravel app which leverages woocommerce for products, categories, media etc. I wondered, what was your process for handling:

- cart (presumably you just build this yourself using the session and not leaning on woocommerce)?
- calculating shipping
- checkout (presumably you simply take payment using laravel and then generate a new order which is sent to woocommerce?)

If you have any useful resources or research that you could share, this would be greatly appreciated.
Many thanks!

**Comment by pixelpeter** [comment]
I'm currently in the process of relaunching my Woocommerce based online shop with the same approach by using Wordpress/Woocommerce only as the backend and building the frontend solely on @Laravel.

For cart functionality I'm using @crinsane https://github.com/Crinsane/LaravelShoppingcart
I also use this for the checkout and then just send the order back with the Woocommerce API

Shipping prices are all still managed in Wordpress/Woocommerce.
Based on the used Wordpress plugin you won't get all prices returned from the Woocommerce API.
That's why I use @jgrossi https://github.com/corcel/corcel to get this information from the specific `post_meta` directly.

Hope this helps

**Comment by admench** [comment]
Fantastic, that is very helpful! Much appreciated. Gives me the confidence to do the same going forward. Is there anything I should be aware of that could cause issues with this setup? It seems like it could provide the best of both worlds.

**Comment by admench** [comment]
Are you building your own shipping class that has logic in to determine how much to charge the customer?

**Comment by pixelpeter** [comment]
Currently this is no issue for me because we offer free shipping ;-)
