### ISSUE TITLE
Giving 500 after migration from local server to a stagging server

### ISSUE THREAD

**Issue by jpeevi** [pixelpeter/laravel5-woocommerce-api-client#43]
Getting:
``` 
Automattic \ WooCommerce \ HttpClient \ HttpClientException (500)
Syntax error
```
After migrating from a local windows server to a live server running cent OS.

**Comment by pixelpeter** [comment]
Please make sure you're running the same Wordpress versions and that your keys are correct

**Comment by jpeevi** [comment]
@pixelpeter Re generated the keys and configured the same , but still the same :(

**Comment by pixelpeter** [comment]
Do you use services like cloudflare? 
Then please disable temporarily and try again.

This are the most common reasons for HttpClientException (500)
- wrong keys
- wrong Wordpress, Woocommerce and API versions
- wrong configured cache services like cloudflare

Additionally you can look at the underlying php library because laravel5-woocommerce-api-client is just a simple wrapper around this and does not add additional functionality

https://github.com/woocommerce/wc-api-php/issues?utf8=%E2%9C%93&q=HttpClientException

**Comment by jpeevi** [comment]
Nope no cloudfare is there any way I can print the complete URL ?

**Comment by pixelpeter** [comment]
Maybe this will help:

use Woocommerce;

// first send a request
Woocommerce::get('orders');

// get the request
Woocommerce::getRequest();

// get the response headers
Woocommerce::getResponse();

**Comment by jpeevi** [comment]
But , Woocommerce::get('orders'); throws the exception!

**Comment by jpeevi** [comment]
Seems to be an issue with WP. Reinstalled a fresh copy and migrated just the product data.
Things are back to normal. Thanks!
